targets:
  $default:
    builders:
      cw_generators|copy_with_annotations:
        enabled: true

builders:
  generators:
    target: ":copy_with_annotations"
    import: "package:cw_generators/builder.dart"
    builder_factories: ["generateSubclass", "generateExtension" ]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
