targets:
  $default:
    builders:
      cw_annotations|cw_annotations:
        enabled: true

builders:
  generators:
    target: ":cw_generators"
    # 1
    import: "lib/builder.dart"
    # 2
    builder_factories: ["generateSubclass", "generateExtension"]
    # 3
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
