targets:
  $default:
    builders:
      cw_generators|cw_annotations:
        enabled: true

builders:
  generators:
    target: ":cw_generators"
    import: "package:cw_generators/builder.dart"
    builder_factories: ["generateSubclass", "generateExtension", "copywith"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
