targets:
  $default:
    builders:
      cw_annotations:


builders:
  cw_annotations:
    import: "package:cw_annotations/annotations.dart"
    builder_factories: ["generateSubclass", "generateExtension"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
