name: cw_generators
description: Getters and setters to save variables to and from Map
version: 1.0.3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build:
  source_gen:
  analyzer:
  cw_annotations:
    git:
      url: https://github.com/postflow/simple_copy_with.git
      ref: main


dev_dependencies:
  build_runner:
  build_test:
  test: ^1.0.0