name: simple_copy_with_generators
description: Generates a copywith method for classes marked @copywith annotation using build_runner
homepage: https://github.com/postflow/simple_copy_with_gen
version: 0.0.2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build: ^2.2.1
  source_gen: ^1.2.1
  analyzer: ^3.0.0
  simple_copy_with_annotations: ^0.0.2
#    git:
#      url: https://github.com/postflow/simple_copy_with.git
#      ref: main


dev_dependencies:
  build_runner:
  build_test:
  test: ^1.0.0