name: generators
description: Getters and setters to save variables to and from Map
version: 1.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
# 1
  build:
# 2
  source_gen:
# 3
  annotations:
    path: ../annotations/


dev_dependencies:
# 4
  build_runner:
# 5
  build_test:
  test: ^1.0.0